apiVersion: apps/v1
kind: Deployment
metadata:
  name: weshare-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: weshare-operator
  template:
    metadata:
      labels:
        name: weshare-operator
    spec:
      serviceAccountName: weshare-operator
      containers:
        - name: weshare-operator
          # Replace this with the built image name
          image: gcr.io/sandbox-bbenlazreg/weshare-operator
          command:
          - weshare-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "weshare-operator"
